dojot/dojot

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
In order to make easier the management and versioning of the microservices;
from defendu release (planned for the first half of 2020) onwards we will
keep all the microservices in this single repository.
This commit rewrites the README, adds codeowners file and adds templates
for issues and pull-requests.
> Refactored the repository to receive the dojot code

- util/microservice-sdk/js/lib/kafka/ConsumerBackPressure.js
Bug fix
When try to resume, this message below appears:
`sdk_1                         | <18:06:00 12/03/2020> -- |undefined -- ERROR: uncaughtException: Cannot read property 'isPaused' of undefined
sdk_1                         | TypeError: Cannot read property 'isPaused' of undefined
sdk_1                         |     at resumeConsumer (/opt/example/lib/kafka/ConsumerBackPressure.js:430:14)
sdk_1                         |     at events.(anonymous function).forEach.handler (/opt/example/node_modules/async/dist/async.js:1254:46)
sdk_1                         |     at …
> fix: [utils/sdk/js] bind, resume in Queue

- subscription-engine/kafka-ws/app/services/TicketService.js
- subscription-engine/kafka-ws/package.json
Fix to recalculate the HMAC token returned by redis to ascertain the integrity and authenticity of the token.
if the token is authentic, the ticket received and the computed ticket will match.
It adds a layer of security when checking the token that was stored in Redis. In this way, we guarantee that no other service has violated the token.
Until then, this verification was not performed
When the service receives the token back, your HMAC is recalculated
* **Does this PR introduce a breaking change?** (What …
> [Fix] to verify the token returned by Redis

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/App.js
- subscription-engine/kafka-ws/docs/apiary.apib
- subscription-engine/kafka-ws/examples/WSClient/Client.js
- subscription-engine/kafka-ws/test/integration/AccessControl.test.js
This PR changes the main endpoint of the kafka-ws component, this is necessary to facilitate redirection through the API Gateway
The main endpoint of the component starts with `/api/**`
The main endpoint of the component will start with `/kafka-ws/**`
This change also affects the API Gateway configuration, but client applications will not change.
This makes it …
> [fix] Endpoint change to facilitate API Gateway redirection

- util/microservice-sdk/js/README.md
- util/microservice-sdk/js/examples/consumer/sample.js
- util/microservice-sdk/js/examples/logging/index.js
- util/microservice-sdk/js/examples/producer/sample.js
- util/microservice-sdk/js/lib/logging/Logger.js
- util/microservice-sdk/js/test/unit/logging/Logger.test.js
Feature.
The logger of the SDK library doesn't set any transport as default, and if the user forgets to set it, the logging messages are printed out in an unexpected format. 
Now the console transport is enabled by default with 'info' logging level. This configuration is used by most of the dojot microservices; so they don't need to worry to set it anymore. Also, the behavior of the method 'setTransport' changed to replace existing configurations. This way, existing code will continue to work.
This commit …
> Feature: sdk logger with default console transport

- util/microservice-sdk/js/README.md
- util/microservice-sdk/js/examples/consumer/sample.js
- util/microservice-sdk/js/examples/logging/index.js
- util/microservice-sdk/js/examples/producer/sample.js
- util/microservice-sdk/js/lib/logging/Logger.js
- util/microservice-sdk/js/test/unit/logging/Logger.test.js
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
Feature
The user is forced to set a logging transport when the SDK is used; otherwise, messages are logged in an unexpected format.
Now the console transport is enabled by default with 'info'
logging level. This configuration is used by most of the
dojot microservices; so they don't need to worry to set it
anymore. Also, the behavior of the method 'setTransport' changed
to …
> Feature: sdk logger with default console transport (#1537)

- connector/mqtt/vernemq/broker/Dockerfile
Bug fix.
VerneMQ Dockerfile entrypoint arguments are not being separated by commas.
Add comma.
No.
> [fix] Missing comma in VerneMQ Dockerfile entrypoint arguments

- connector/mqtt/locust/Docker/docker-compose-master.yml
- connector/mqtt/locust/Docker/docker-compose-slave.yml
- connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
- connector/mqtt/locust/requirements/prod.txt
- connector/mqtt/locust/src/ejbca/cert_utils.py
- connector/mqtt/locust/src/ejbca/certificate.py
- connector/mqtt/locust/src/mqtt_locust/mqtt_client.py
- connector/mqtt/locust/tests/ejbca/test_certificate.py
- connector/mqtt/locust/tests/mqtt_locust/test_mqtt_client.py
Bug fix
1. Locust throws an error when initializing
2. Revoke is not working
3. Renew is not working
1. Locust does not throw an error when initializing, the problem is gevent version is not fixed in Locust 0.12.2 (it is fixed in later versions)
2. Revoke is working - missing slash in the URL was preventing it from working
3. Renew is working - it was trying to revoke twice, so the second call to EJBCA was returning 404, thus failing
* **Does this PR introduce a breaking change?** (What changes might users …
> [fix] Fixes Locust problems with revoke, renew and gevent version

- x509-identity-mgmt/Dockerfile
- x509-identity-mgmt/ejbca/README.md
- x509-identity-mgmt/ejbca/bin/dojot-custom/configuration-variables.sh
- x509-identity-mgmt/ejbca/bin/dojot-custom/exec.sh
k8s fix
The current behavior is that, during the creation of the docker image (via Dockerfile) the profile files are copied to a directory that is also mapped as a volume, however, as the volume does not yet exist, this is a problem when we try to run the container in a Kubernetes environment.
Because the Dockerfile is copying the EJBCA certificate profiles to a directory that was also mapped as a volume on Kubernetes, it was necessary to change the location of the directory into the container.
* **Does this …
> Changing the location of the profiles directory

- x509-identity-mgmt/README.md
docs update
It is not clear how to recover the fingerprint after the certificate is saved to disk
Documentation on how to use openssl to retrieve the certificate fingerprint.
no
commit brought in from PR:
#1616
> improved documentation x509-identity-mnmt (branch "development")

- connector/mqtt/locust/Docker/docker-compose-master.yml
- connector/mqtt/locust/Docker/docker-compose-slave.yml
- connector/mqtt/locust/Docker/scripts/generate_certs/Dockerfile
- connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
- connector/mqtt/locust/master_entrypoint.sh
- connector/mqtt/locust/slave_entrypoint.sh
- connector/mqtt/locust/src/config.py
Bug fix and enhancement
- Generate certs script image is being retrieved from Dojot Docker Hub, but it is not necessary to send the image to it
- All Docker Compose files were creating volumes for all files and directories, but this is necessary only when developing
- Generate certs image can now be built locally
- Docker Compose files have now a commented volume for developers and has only the `cert` directory mapped by default
- Fixed environment variables with wrong default values (such as REDIS_HOST …
> [release] Fix Locust Docker files

- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkBrokerCertHasRevoke.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkExpirationCertificate.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCRL.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/vmq_dojot.sh
Bugfix
When the certificate renewal script was run, it created more `supercronic` processes
At any given time, there were so many `supercronic` processes that this increased the broker's memory and overloaded the certificate issuing service to the point of reaching 100% CPU.
Now, if there is already a `supercronic` process running, it does not create a new.
With that, we no longer have the problem of increasing memory and CPU at 100% processing
* **Does this PR introduce a breaking change?** (What changes …
> [Development] fix supercronic processes created a lot

- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkBrokerCertHasRevoke.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkExpirationCertificate.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCRL.sh
- connector/mqtt/vernemq/broker/bin/vmq_dojot/vmq_dojot.sh
Bugfix
When the certificate renewal script was run, it created more `supercronic` processes
At any given time, there were so many `supercronic` processes that this increased the broker's memory and overloaded the certificate issuing service to the point of reaching 100% CPU.
Now, if there is already a `supercronic` process running, it does not create a new.
With that, we no longer have the problem of increasing memory and CPU at 100% processing
* **Does this PR introduce a breaking change?** (What changes …
> [Release] fix supercronic processes created a lot

- subscription-engine/kafka-ws/index.js
Bug fix
The kafka-ws process fails to create a consumer kafka and runs, but without returning anything to websocket clients.
End kafka-ws process when a rejected promise is not handled anywhere
dojot/dojot#1825
This is a workaround for the problem
> [Release-v0.5.0] End kafka-ws process when a rejected promise is not handled anywhere

- connector/mqtt/locust/Docker/scripts/generate_certs/Dockerfile
- connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
Enhancement.
We are using the Python image, but the problem is that the image can take so much time to build because of the Locust library installation.
We changed the base image to the dojot/locust one, so we don't have to install the Locust lib every time.
It also add new volumes in the generate-certs Docker Compose.
No.
* **Is there any issue related to this PR?** (Link to an issue, …
> [locust] Change generate-certs base image to the Locust one

- storage/time-series/influxdb/retriever/api/v1.yml
from https://swagger.io/docs/specification/serialization/
> Additionally, the allowReserved keyword specifies whether the reserved characters :/?#[]@!$&'()*+,;= in parameter values are allowed to be sent as they are, or should be percent-encoded. By default, allowReserved is false, and …
> [v0.5.1] [influxdb-retriever] Allow Reserved for date-time

- storage/time-series/influxdb/retriever/api/v1.yml
from https://swagger.io/docs/specification/serialization/
> Additionally, the allowReserved keyword specifies whether the reserved characters :/?#[]@!$&'()*+,;= in parameter values are allowed to be sent as they are, or should be percent-encoded. By default, allowReserved is false, and …
> [dev] [influxdb-retriever] Allow Reserved for date-time

- tools/certgen/LICENSE
- tools/certreq/LICENSE
- tools/kafka/loopback/LICENSE
The following tools are licensed under Apache License:
- certgen
- certreq
- kafka-loopback
It licenses dojot tools under Apache License
NA
NA
No
dojot/dojot#1879
> Licensed the dojot tools under Apache License, version 2.0

- connector/mqtt/vernemq/broker/bin/vmq_dojot/vmq_dojot.sh
- connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/ejbca_client.sh
- connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/ejbca_client.sh
Bug fix
VerneMQ, V2K and K2V were checking that the x509-identity-mgmt was standing, but at an endpoint that no longer exists.
A workaround was made to verify that the x509-identity-mgmt is ready. This solution was made because it is not yet known whether the health check port will be opened in the kubernetes.
* **Is there any issue related to this PR? (Link to an issue, e.g. #99999)** …
> [development][fix] check x509-identity-mgmt readiness

- iam/x509-identity-mgmt/README.md
- iam/x509-identity-mgmt/js/config/default.conf
- iam/x509-identity-mgmt/js/schemas/change-owner-certificate.json
- iam/x509-identity-mgmt/js/schemas/defs.json
- iam/x509-identity-mgmt/js/schemas/register-or-generate-certificate.json
- iam/x509-identity-mgmt/js/schemas/register-trusted-ca-certificate.json
- iam/x509-identity-mgmt/js/schemas/update-trusted-ca-certificate.json
- iam/x509-identity-mgmt/js/src/DIContainer.js
- iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrProvider.js
- iam/x509-identity-mgmt/js/src/services/CertificateService.js
- iam/x509-identity-mgmt/js/src/services/TrustedCAService.js
- iam/x509-identity-mgmt/js/tests/json-schema/certificates.test.js
- iam/x509-identity-mgmt/js/tests/json-schema/trustedCAs.test.js
- iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrProvider.test.js
- iam/x509-identity-mgmt/js/tests/unitary/services/CertificateService.test.js
feature
The service always performed validations on the SubjectDN of the informed CSR to obtain a certificate signed by the platform.
These validations forced the user to set on the SubjectDN `Common Name` an existing and valid device ID for the current tenant.
As the association of devices with certificates is no longer done by the `Common Name` due to the support for external certificates, these checks were disabled by default.
* **Does this PR introduce a breaking change?** (What changes might users need to …
> Flag-enabled SubjectDN and DeviceExists validations

- tools/cert-sidecar/README.md
- tools/cert-sidecar/app/App.js
- tools/cert-sidecar/app/CronsCertsMgmt.js
- tools/cert-sidecar/app/certificatesMgmt/Certificates.js
- tools/cert-sidecar/app/certificatesMgmt/index.js
- tools/cert-sidecar/app/x509IdentityMgmt/Requests.js
- tools/cert-sidecar/app/x509IdentityMgmt/index.js
- tools/cert-sidecar/config/default.conf
- tools/cert-sidecar/config/development.conf
- tools/cert-sidecar/package-lock.json
- tools/cert-sidecar/package.json
- tools/cert-sidecar/test/integration/CertificatesMgmt.test.js
- tools/cert-sidecar/test/integration/X509IdentityMgmt.test.js
- tools/cert-sidecar/test/unit/App.test.js
- tools/cert-sidecar/test/unit/CronsCertsMgmt.test.js
feature
The `cert-side` service only retrieves the root CA certificate from the dojot platform. 
It does not retrieve certificates from external CAs trusted by the platform.
The `cert-side` service starts to retrieve the bundle of CAs trusted by the platform, this bundle also contains the CA certificate from dojot, thus, the functionality of retrieving only the platform CA certificate becomes unnecessary when supporting external certificates. 
* **Does this PR introduce a breaking change?** (What changes might …
> [cert-sidecar] Obtaining the CA bundle file

- iam/x509-identity-mgmt/js/src/express/routes/contentNegotiation.js
- iam/x509-identity-mgmt/js/src/express/routes/throwAwayRoutes.js
- iam/x509-identity-mgmt/js/tests/unitary/express/routes/throwAwayRoutes.test.js
feature
The service currently provides response content only in JSON format
In addition to the JSON format, the service now responds by default in the PEM-File format
The other services that use internal endpoints (`cert-sidecar` service) must provide the `Accept: application/json` header to continue to receive data in JSON format, otherwise, they will receive it in …
> [x509-identity-mgmt] Support for content negotiation on internal endpoints

- tools/cert-sidecar/README.md
- tools/cert-sidecar/app/certificatesMgmt/Certificates.js
- tools/cert-sidecar/config/default.conf
- tools/cert-sidecar/test/integration/CertificatesMgmt.test.js
configuration update
There was an additional parameter to inform the name of the application to which the certificate retrieved by the sidecar would be associated with.
The additional parameter was removed, as there was no need for it, since there was already a correct parameter for this.
dojot/dojot##1940
* …
> [cert-sidecar] Configuration parameter changed (Name of the application in which the sidecar will be associated)

- tools/cert-sidecar/config/default.conf
config update
Certificate request timeout is 1 second
The certificate request timeout should be more conservative, in 10 seconds
no
The timeout problem was observed when developing the ticket:
dojot/dojot#1940
The reason for this change is that the first certificate (when the EJBCA …
> [cert-sidecar] Increasing the request cert timeout

- x509-identity-mgmt/ejbca/bin/dojot-custom/exec.sh
Bug fix
The problem is that when the EJBCA container is dropped, the new one that is created does not have the configuration file for issuing certificates with more secure keys.
The fix causes the configuration file to be recreated for each new container.
dojot/dojot#2083
Branch …
> [rel/v0.6.0] Correction of EJBCA script

- connector/mqtt/vernemq/v2k-bridge/app/Utils.js
- connector/mqtt/vernemq/v2k-bridge/test/unit/AgentMessenger.test.js
- connector/mqtt/vernemq/v2k-bridge/test/unit/Utils.test.js
If there is a timestamp in the original message, it will be used;
otherwise, it will be used the current time.
Bugfix
The current time is not being used as timestamp when the original messages hasn't got a valid timestamp.
Fixed the problem reported above.
No.
Related to #2186
> Refactored the process of including a timestamp

- .github/workflows/file-mgmt.yml
The file-mgmt service don't have an action for push documentation (GH pages)
Now the file-mgmt service has GitHub Actions for GH pages
No
> [ file-mgmt ] - GitHub Actions - GH Pages

- connector/mqtt/vernemq/broker/Dockerfile
- connector/mqtt/vernemq/broker/src/dojot_acl_plugin/rebar.config
- connector/mqtt/vernemq/broker/src/dojot_acl_plugin/rebar.lock
- connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/rebar.config
- connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/rebar.lock
- connector/mqtt/vernemq/broker/vernemq-1.10.0-deprecate-git-protocol.patch
Bugfix
It's not able to build vernemq image because it makes use of deprecated git protocol.
Now, it's possible to build vernemq image because it's using https instead of git protocol.
No
> [VerneMQ] Deprecate unencrypted git protocol use

- storage/time-series/influxdb/retriever/app/influx/DeviceDataRepository.js
- storage/time-series/influxdb/retriever/config/default.conf
Quando o telegraf salva uma string no influxDB, ele a mantém como string "simples", tendo apenas um par de aspas
Em contraste com a forma que o storer armazenava: escapando aspas dentro da string, conforme print
Por conta disso, ao tentar fazer um JSON.parse da string nova, o retriever quebrava.
Foi retirado o código desse parsing, que no cenário atual não é mais necessário
> Corrige quebra na leitura de string pelo retriever
