- README.md
This adds a new suggestion for the issue tracking repo README file,
with a slightly more approachable version.
> Updates readme with a more friendly message

- util/microservice-sdk/js/.dockerignore
- util/microservice-sdk/js/.gitignore
> chore: [utils/sdk/js] add ignore

- .github/workflows/tools-kafka-loopback.yml
- tools/kafka/loopback/Dockerfile
- tools/kafka/loopback/README.md
- tools/kafka/loopback/bin/entrypoint.sh
feature
Adds an initial version of the loopback service (Kafka tool) and a GitHub action to push it to Dockerhub. Redirect messages from a topic to another in a dojot style.
> feat: [tools/kafka/loopback] added loopback service

- connector/mqtt/locust/src/dojot/api.py
Bug fix
The variable res is not defined in the scope when it is being accessed in a catch statement, nor it is being checked for definition.
Those problems are solved.
No.
> [mqtt/locust] Variable not defined

- connector/mqtt/vernemq/k2v-bridge/Dockerfile
- connector/mqtt/vernemq/k2v-bridge/app/AgentMessenger.js
- connector/mqtt/vernemq/k2v-bridge/app/MqttClient.js
- connector/mqtt/vernemq/k2v-bridge/app/utils.js
- connector/mqtt/vernemq/k2v-bridge/package-lock.json
- connector/mqtt/vernemq/k2v-bridge/package.json
- connector/mqtt/vernemq/k2v-bridge/test/unit/agentMessenger.test.js
- connector/mqtt/vernemq/k2v-bridge/test/unit/mqttClient.test.js
- connector/mqtt/vernemq/k2v-bridge/test/unit/utils.test.js
Bug fix and enhancement.
The process hangs when the VerneMQ connection is down, preventing the K2V from connecting to the broker.
The process does not hang anymore.
No.
The MQTT lib has been updated.
> Process hangs when broker connection is down

- connector/mqtt/vernemq/broker/Dockerfile
Add tini to VerneMQ image.
The VerneMQ process has the PID 1. This caused some problems in some tests, because there were a lot of zombie processes blocking resources.
There were no zombie processes after tini.
No.
> Add tini to VerneMQ

- connector/mqtt/vernemq/v2k-bridge/app/MQTTClient.js
- connector/mqtt/vernemq/v2k-bridge/package-lock.json
- connector/mqtt/vernemq/v2k-bridge/package.json
- connector/mqtt/vernemq/v2k-bridge/test/unit/MqttClient.test.js
Enhancement
The MQTT library version is 3.0.0 and there is no error handling.
The MQTT library version is 4.1.0 and there is error handling.
No.
> Update MQTT library version in V2K

- connector/mqtt/locust/Docker/docker-compose-master.yml
- connector/mqtt/locust/Docker/docker-compose-slave.yml
- connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
- connector/mqtt/locust/requirements/prod.txt
Bug fix.
Locust does not fixed gevent version, so it downloads the latest and breaks the code.
Gevent is now fixed to version 1.4.0.
No.
> [fix] Gevent version is not fixed in Locust

- x509-identity-mgmt/ejbca/bin/dojot-custom/exec.sh
fix
It is not possible to enable debug for scripts
Uses an environment variable to enable debug mode
no
> treatment to enable debugging in custom scripts for dojot

- subscription-engine/kafka-ws/Dockerfile
- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/App.js
- subscription-engine/kafka-ws/app/Config.js
- subscription-engine/kafka-ws/app/Redis/RedisExpireMgmt.js
- subscription-engine/kafka-ws/app/Redis/RedisManager.js
- subscription-engine/kafka-ws/app/Terminus.js
- subscription-engine/kafka-ws/app/Utils.js
- subscription-engine/kafka-ws/app/WebsocketTarball.js
- subscription-engine/kafka-ws/app/routes/AccessControlRouter.js
- subscription-engine/kafka-ws/app/routes/TicketRouter.js
- subscription-engine/kafka-ws/app/routes/TopicsRouter.js
- subscription-engine/kafka-ws/app/services/TicketService.js
- subscription-engine/kafka-ws/docs/apiary.apib
- subscription-engine/kafka-ws/examples/README.md
- subscription-engine/kafka-ws/examples/WSClient/Client.js
- subscription-engine/kafka-ws/examples/WSClient/package-lock.json
- subscription-engine/kafka-ws/examples/WSClient/package.json
- subscription-engine/kafka-ws/examples/docker-compose.yml
- subscription-engine/kafka-ws/index.js
- subscription-engine/kafka-ws/jest.setup.js
- subscription-engine/kafka-ws/package-lock.json
- subscription-engine/kafka-ws/package.json
- subscription-engine/kafka-ws/test/integration/AccessControl.test.js
- subscription-engine/kafka-ws/test/integration/WSServer.test.js
- subscription-engine/kafka-ws/test/unit/Utils.test.js
> chore: [subscription-engine/kafka-ws] Add ticket feature in kafka-ws from dev

- subscription-engine/kafka-ws/README.md
> chore: Add note kong

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/App.js
- subscription-engine/kafka-ws/app/Config.js
- subscription-engine/kafka-ws/app/Kafka/KafkaConsumer.js
- subscription-engine/kafka-ws/app/Kafka/KafkaTopicsConsumerCallbacksMgmt.js
- subscription-engine/kafka-ws/app/Redis/RedisExpireMgmt.js
- subscription-engine/kafka-ws/app/Redis/RedisManager.js
- subscription-engine/kafka-ws/app/Terminus.js
- subscription-engine/kafka-ws/app/WebsocketTarball.js
- subscription-engine/kafka-ws/app/WhereProcessing/WhereParser.js
- subscription-engine/kafka-ws/app/services/TicketService.js
- subscription-engine/kafka-ws/index.js
Enhancement
Small fixes to the code, like adding correct names for loggers and changing `process.exit(1)` to `process.kill(process.pid)`.
No.
> [subscription-engine] Small fixes

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/App.js
- subscription-engine/kafka-ws/app/Config.js
- subscription-engine/kafka-ws/app/Kafka/KafkaConsumer.js
- subscription-engine/kafka-ws/app/Kafka/KafkaTopicsConsumerCallbacksMgmt.js
- subscription-engine/kafka-ws/app/Redis/RedisExpireMgmt.js
- subscription-engine/kafka-ws/app/Redis/RedisManager.js
- subscription-engine/kafka-ws/app/Terminus.js
- subscription-engine/kafka-ws/app/WebsocketTarball.js
- subscription-engine/kafka-ws/app/WhereProcessing/WhereParser.js
- subscription-engine/kafka-ws/app/services/TicketService.js
- subscription-engine/kafka-ws/index.js
Enhancement
Small fixes to the code, like adding correct names for loggers and changing `process.exit(1)` to `process.kill(process.pid)`.
No.
> [kafka-ws] [release] Small fixes

- .github/workflows/kafka-ws.yml
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
Bug fix
> Add tag name to github workflow in kafka-ws

- connector/mqtt/vernemq/README.md
> doc: mosquitto_sub wrong topic

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/Config.js
- subscription-engine/kafka-ws/index.js
> Add environment variable to enable requesting certificates from client

- codecov.yml
Codecov settings update
Codecov is monitoring directories that do not need to be covered by it.
Codecov stops monitoring directories that do not need to be covered by it.
no
PR #1598 cannot pass because the codecov is expecting a test coverage result, but the code is a Bash script.
> update codecov settings

- connector/mqtt/vernemq/v2k-bridge/app/AgentMessenger.js
> improve debug when trying send msg to kafka 

- connector/mqtt/vernemq/k2v-bridge/README.md
> doc: fix default Kafka consumption topic variable value

- tools/certgen/README.md
- tools/certgen/bin/certgen.sh
- tools/certreq/README.md
- tools/certreq/bin/certreq.sh
No
Bringing to this branch the PRs:
https://github.com/dojot/dojot/pull/1619
https://github.com/dojot/dojot/pull/1598
> Bringing CertTools from "development" to "feature 0.5.0"

- connector/mqtt/vernemq/v2k-bridge/README.md
> Review V2K documentation for v0.5.0 release

- connector/mqtt/locust/src/dojot/api.py
- connector/mqtt/locust/src/ejbca/cert_utils.py
- connector/mqtt/locust/src/ejbca/certificate.py
- connector/mqtt/locust/src/mqtt_locust/redis_client.py
- connector/mqtt/locust/src/scripts/generate_certs.py
- connector/mqtt/locust/src/utils.py
- connector/mqtt/locust/tests/dojot/test_api.py
- connector/mqtt/locust/tests/ejbca/test_cert_utils.py
Bug fix
Multiple fixes to generate_certs, such as error handling, logs.
https://github.com/dojot/dojot/issues/1681
> Enhancements to generate_certs script

- tools/kafka/loopback/README.md
> [dev] Review Loopback documentation

- connector/mqtt/vernemq/k2v-bridge/README.md
> [dev] Review K2V documentation

- subscription-engine/kafka-ws/app/Conditions/Conditions.js
- subscription-engine/kafka-ws/app/WhereProcessing/OperatorValidator.js
- subscription-engine/kafka-ws/test/integration/Conditions.test.js
Bug fix, better description in the issue linked above.
The bug is now fixed and the tests for conditions has been remade.
https://github.com/dojot/dojot/issues/1714
> [dev] Correct problems with the value 0

- subscription-engine/kafka-ws/app/Conditions/Conditions.js
- subscription-engine/kafka-ws/app/WhereProcessing/OperatorValidator.js
- subscription-engine/kafka-ws/test/integration/Conditions.test.js
Bug fix, better description in the issue linked above.
The bug is now fixed and the tests for conditions has been remade.
https://github.com/dojot/dojot/issues/1714
> [v0.5.0] Correct problems with the value 0

- x509-identity-mgmt/js/apidocs/api-description.apib
docs update
Nothing mentioned about error status (4xx)
I wrote a little bit about error status
no
dojot/dojot#1584
> [release v0.5.0][x509-identity-mgmt] A little bit about error responses in the API documentation

- x509-identity-mgmt/js/apidocs/api-description.apib
docs update
Nothing mentioned about error status (4xx)
I wrote a little bit about error status
no
dojot/dojot#1584
> [development][x509-identity-mgmt] A little bit about error responses in the API documentation

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/Errors/ErrorCodes.js
- subscription-engine/kafka-ws/docs/apiary.apib
> [dev] Update API documentation

- connector/mqtt/locust/README.md
- connector/mqtt/locust/src/scripts/README.md
> [v0.5.0] Review Locust Documentation

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/Errors/ErrorCodes.js
- subscription-engine/kafka-ws/docs/apiary.apib
> [v0.5.0] Update Kafka WS API documentation

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/docs/apiary.apib
Docs update, this correction was applied in https://github.com/dojot/dojot/pull/1757 and needed to be in dev too.
> [dev] Fix in Kafka WS documentation

- connector/kafka2ftp/README.md
> [v0.5.0] Review readme from kafka2ftp

- connector/kafka2ftp/README.md
> [dev] Review readme from kafka2ftp

- .github/workflows/connector-kafka2ftp.yml
- .github/workflows/connector-mqtt-latency-pub-test-prometheus.yml
- .github/workflows/k2v-bridge.yml
- .github/workflows/kafka-ws.yml
- .github/workflows/locust.yaml
- .github/workflows/v2k-bridge.yml
- .github/workflows/x509-identity-mgmt.yml
In codecov token not required for repositories uploading GitHub Actions anymore.
> [dev] remove token codecov

- .github/workflows/connector-kafka2ftp.yml
- .github/workflows/connector-mqtt-latency-pub-test-prometheus.yml
- .github/workflows/k2v-bridge.yml
- .github/workflows/kafka-ws.yml
- .github/workflows/locust.yaml
- .github/workflows/v2k-bridge.yml
- .github/workflows/x509-identity-mgmt.yml
In codecov token not required for repositories uploading GitHub Actions anymore.
> [v0.5.0]  Remove token codecov

- .github/workflows/v2k-bridge.yml
> Fix: codecov v2k 

- connector/mqtt/vernemq/v2k-bridge/README.md
- connector/mqtt/vernemq/v2k-bridge/config/default.conf
- connector/mqtt/vernemq/v2k-bridge/config/docker.conf
Bug fix
The env var that some parameters in `default.conf` use is HOSTNAME.
The correct env var is V2K_APP_HOSTNAME.
This PR also includes a `docker.conf` file.
No.
> Fix env var in default.conf

- connector/mqtt/vernemq/v2k-bridge/README.md
> [v2k-bridge] Correct links in README

- subscription-engine/kafka-ws/Dockerfile
- subscription-engine/kafka-ws/bin/entryPoint.sh
- subscription-engine/kafka-ws/examples/Without Dojot/docker-compose.yml
> [realease/v0.5.0] Added entrypoint script

- keycloak/admin.json
Create a new public client called "gui" and add a new mapper to show the "username" claim in access token. This last was necessary because the flowbroker service uses this information to work.
> Update Default Realm

- .github/workflows/keycloak.yml
The unit test "DefaultHttpClientFactoryTest.createHttpClientProviderWithUnvailableURL" result is intermittent, for now let's skip it.
> Fix test error

- subscription-engine/kafka-ws/Dockerfile
- subscription-engine/kafka-ws/app/Kafka/KafkaConsumer.js
- subscription-engine/kafka-ws/bin/entryPoint.sh
- subscription-engine/kafka-ws/config/default.conf
- subscription-engine/kafka-ws/examples/Without Dojot/docker-compose.yml
- subscription-engine/kafka-ws/index.js
- subscription-engine/kafka-ws/package-lock.json
- subscription-engine/kafka-ws/package.json
Added entrypoint script
Surround with try catch websocketTarball initialization
Fix kafkaConsumer construtor initialization
Added tini in docker file
> [development] Fix and improvement kafkaWS

- storage/time-series/influxdb/retriever/doc.html
> add html to influxdb retriever

- subscription-engine/kafka-ws/LICENSE-2.0.txt
- subscription-engine/kafka-ws/license-exceptions.json
- subscription-engine/kafka-ws/package-lock.json
- subscription-engine/kafka-ws/package.json
Changed the kafka-ws license from GPL-3.0 to Apache-2.0
NA
NA
NA
No
> Changed kafka-ws license to Apache 2.0

- connector/mqtt/vernemq/v2k-bridge/LICENSE-2.0.txt
- connector/mqtt/vernemq/v2k-bridge/license-exceptions.json
- connector/mqtt/vernemq/v2k-bridge/package-lock.json
- connector/mqtt/vernemq/v2k-bridge/package.json
From now on this service is licensed as Apache-2.0.
Changed the V2K license from GPL-3.0 to Apache-2.0
NA
NA
NA
No
> Changed v2k license to Apache-2.0

- connector/mqtt/vernemq/k2v-bridge/LICENSE-2.0.txt
- connector/mqtt/vernemq/k2v-bridge/license-exceptions.json
- connector/mqtt/vernemq/k2v-bridge/package-lock.json
- connector/mqtt/vernemq/k2v-bridge/package.json
From now on this service is licensed as Apache-2.0.
Changed the k2v license from GPL-3.0 to Apache-2.0
NA
NA
NA
No
> Changed the k2v license to Apache-2.0

- storage/time-series/influxdb/retriever/app/express/routes/v1/Devices.js
- storage/time-series/influxdb/retriever/app/influx/DataQuery.js
- storage/time-series/influxdb/retriever/test/unit/InfluxDataQuery.test.js
> [v0.5.1 - influxdb-retriever] Fix:  Pagination and offset

- storage/time-series/influxdb/retriever/app/express/routes/v1/Devices.js
- storage/time-series/influxdb/retriever/app/influx/DataQuery.js
- storage/time-series/influxdb/retriever/test/unit/InfluxDataQuery.test.js
> [dev - influxdb-retriever] Fix: Pagination and offset

- connector/mqtt/locust/LICENSE
- connector/mqtt/locust/NOTICE
It licenses the *Dojot Loat Test* under Apache License.
NA
NA
No
dojot/dojot#1879
> Licensed 'Dojot Load Test' under Apache License, Version 2.0

- LICENSE
- README.md
- Removed mentions to GPL License
- Added Apache LICENSE file
NA
NA
No
dojot/dojot#1879
> Updated README file and added LICENSE file

- README.md
It updates documentation.
NA
NA
No
dojot/dojot#1879
> Updated Readme file with licenses information

- storage/time-series/influxdb/example/init-influx.sh
- storage/time-series/influxdb/storer/README.md
> [influxdb-storer] Improve readme

- connector/mqtt/vernemq/broker/bin/NOTICE
- connector/mqtt/vernemq/broker/bin/vernemq.sh
> fixed vernemq script

- connector/mqtt/vernemq/broker/bin/NOTICE
- connector/mqtt/vernemq/broker/bin/vernemq.sh
> [dev] fix vernemq, vernemq.sh script and notice

- storage/time-series/influxdb/example/docker-compose.yml
- storage/time-series/influxdb/example/init-influx.sh
> [InfluxDB][Example] fix: Removes verification that it is onboarded and changes to maximum attempts

- subscription-engine/kafka-ws/index.js
Fix config manager config build on kafka-ws
> [v0.6.0] Fixed configManager json build

- subscription-engine/kafka-ws/Dockerfile
fix kafka ws healthcheck enpoint in Dockerfile
> [v0.6] fix healthcheck kafkaws v0.6

- subscription-engine/kafka-ws/Dockerfile
fix kafka ws healthcheck enpoint in Dockerfile
> [dev] fix healthcheck kafka-ws

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/Redis/RedisManager.js
- subscription-engine/kafka-ws/config/default.conf
- subscription-engine/kafka-ws/test/unit/RedisManager.test.js
- [x ] Tests for the changes have been added (for bug fixes / features)
The kafka ws strategy behavior was not not working properly, cause typo and business rules.
#2045 
> [v0.6.0][kafka-ws] improved redis retry strategy

- subscription-engine/kafka-ws/README.md
- subscription-engine/kafka-ws/app/Redis/RedisManager.js
- subscription-engine/kafka-ws/config/default.conf
- subscription-engine/kafka-ws/test/unit/RedisManager.test.js
- [x ] Tests for the changes have been added (for bug fixes / features)
The kafka ws strategy behavior was not not working properly, cause typo and business rules.
#2045 
> [dev][kafka-ws] improved redis retry strategy

- tools/cert-sidecar/README.md
- tools/cert-sidecar/config/default.conf
Currently runs every 1 minute after X hour
Must run every X hours
https://www.npmjs.com/package/cron#cron-ranges
https://crontab.guru/#0_*/2_*_*_*
> [cert-sidecar] fix: cron expression

- tools/cert-sidecar/README.md
docs update
Included the link to the x509-identity-mgmt schema that lists the values accepted in the `certs.belongsto.application` configuration field.
> [cert-sidecar] documentation improvement

- .github/workflows/kafka-ws.yml
> [v0.6.0] Remove github token usage in kafka-ws actions and update action version

- .github/workflows/kafka-ws.yml
> [dev] Remove github token usage in kafka-ws actions and update action version

- .github/workflows/certificate-acl.yml
> [certificate-acl] Rename the acl docker image

- connector/mqtt/vernemq/v2k-bridge/Dockerfile
Bugfix
The healthcheck is not working in the v2k docker container.
Fixed the healthcheck in the v2k docker container
No
> Fixed healthcheck in the Dockerfile for v2k service

- connector/mqtt/vernemq/k2v-bridge/Dockerfile
- connector/mqtt/vernemq/v2k-bridge/Dockerfile
Bugfix
The healthcheck is not working in the k2v docker container.
Fixed the healthcheck in the k2v docker container
No
> Fixed healthcheck in the Dockerfile for k2v service

- tools/certreq/bin/certreq.sh
> certreq: add belongs update

- connector/mqtt/vernemq/k2v-bridge/npm-debug.log
- connector/mqtt/vernemq/v2k-bridge/app/Utils.js
- connector/mqtt/vernemq/v2k-bridge/test/unit/Utils.test.js
> Hotfix: Service ignores timestamp sent by device

- .github/workflows/file-mgmt.yml
- storage/file/minio/file-mgmt/tests/integration/file-listing-route-test.spec.js
- storage/file/minio/file-mgmt/tests/integration/file-removal-route-test.spec.js
- storage/file/minio/file-mgmt/tests/integration/file-retrieval-route-test.spec.js
- storage/file/minio/file-mgmt/tests/integration/file-upload-route-test.spec.js
- storage/file/minio/file-mgmt/tests/integration/setup.js
Now the file-mgmt service has GitHub Actions
file-mgmt service doesn't have GitHub Actions
Now the file-mgmt service has GitHub Actions for unit tests and docker image push
No
> [ file-mgmt ] - GitHub Actions

- .github/workflows/file-mgmt.yml
- storage/file/minio/file-mgmt/README.md
> Action filemgmt

- connector/http-agent/.eslintrc.json
- connector/http-agent/app/Utils.js
- connector/http-agent/app/express/interceptors/deviceIdentification.js
- connector/http-agent/app/express/routes/v1/IncomingMessages.js
- connector/http-agent/license-exceptions.json
- connector/http-agent/package-lock.json
- connector/http-agent/package.json
- connector/http-agent/test/integration/IncomingMessages.test.js
- connector/http-agent/test/unit/Util.test.js
* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
* #2319
* #2305 
* #2306
* #2315 
>  fix: util timestamp and response status codes

- connector/http-agent/README.md
- connector/http-agent/app/App.js
- connector/http-agent/app/axios/CertificateAclService.js
- connector/http-agent/app/axios/createAxios.js
- connector/http-agent/app/express/index.js
- connector/http-agent/app/express/interceptors/deviceIdentification.js
- connector/http-agent/app/express/interceptors/identificationService.js
- connector/http-agent/app/express/routes/v1/IncomingMessages.js
- connector/http-agent/app/express/schemas/messageSchema.js
- connector/http-agent/config/default.conf
- connector/http-agent/example/docker-compose/docker-compose.yml
- connector/http-agent/package-lock.json
- connector/http-agent/test/integration/IncomingMessages.test.js
- connector/http-agent/test/unit/App.test.js
- connector/http-agent/test/unit/Cache.test.js
- connector/http-agent/test/unit/CertificateAclService.test.js
* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
* #2353
> fix: error message with a wrong parameter

- iam/device-basic-authentication/app/kafka/ConsumerMessages.js
- iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrEventEngine.js
- iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrProvider.js
- iam/x509-identity-mgmt/js/src/express/interceptors/scopedDIInterceptor.js
- iam/x509-identity-mgmt/js/src/notifications/NotificationEngine.js
- iam/x509-identity-mgmt/js/src/notifications/OwnershipNotifier.js
- iam/x509-identity-mgmt/js/src/notifications/TrustedCANofitier.js
- iam/x509-identity-mgmt/js/src/services/CertificateService.js
- iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrProvider.test.js
- iam/x509-identity-mgmt/js/tests/unitary/express/interceptors/scopedDIInterceptor.test.js
- iam/x509-identity-mgmt/js/tests/unitary/notifications/NotificationEngine.test.js
- iam/x509-identity-mgmt/js/tests/unitary/notifications/OwnershipNotifier.test.js
- iam/x509-identity-mgmt/js/tests/unitary/notifications/TrustedCANofitier.test.js
- iam/x509-identity-mgmt/js/tests/unitary/services/CertificateService.test.js
> Feature: Correlation id received must be passed on in other communications

- connector/http-agent/app/express/routes/v1/IncomingMessages.js
> fix: device data message generation

- connector/mqtt/locust/master_entrypoint.sh
fix locust master initialization
fix  #2424
> fix initialization: add support to redis 6.2.6

- connector/http-agent/app/Server.js
- connector/http-agent/app/Utils.js
- connector/http-agent/test/unit/Util.test.js
* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
#2318 
#2426 
> FIx reload certificate with external ca

- connector/http-agent/app/express/routes/v1/IncomingMessages.js
- connector/http-agent/package-lock.json
- connector/http-agent/test/integration/IncomingMessages.test.js
* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
* #2415 
> fix: timestamp error catch in create-many

- storage/time-series/influxdb/retriever/app/sync/DeviceManagerService.js
- storage/time-series/influxdb/retriever/test/unit/DeviceManagerService.spec.js
> [influxdb-retriever] Fix: synchronization with device-manager 

- connector/http-agent/README.md
- connector/http-agent/app/Server.js
- connector/http-agent/app/Utils.js
- connector/http-agent/config/default.conf
- connector/http-agent/package-lock.json
- connector/http-agent/test/unit/Server.test.js
- connector/http-agent/test/unit/Util.test.js
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)
Bugfixes
External certificates are only accepted if the service is restarted.
External certificates are accepted without restarting the service.
No.
> [HTTP-AGENT] Hotfixes - External Certificates

- storage/file/minio/file-mgmt/src/config/default.conf
- storage/file/minio/file-mgmt/src/index.js
- storage/file/minio/file-mgmt/src/utils/load-secrets-util.js
- storage/file/minio/file-mgmt/tests/units/others/load-secrets-util-test.spec.js
> [file-mgmt] fix: secrets loader

- tools/cert-sidecar/config/default.conf
> [Cert-sidecar] cron expiration is true by default

- storage/file/minio/file-mgmt/src/app/web/interceptors/busboy-interceptor.js
- storage/file/minio/file-mgmt/src/minio/minio-repository.js
- storage/file/minio/file-mgmt/tests/units/interceptors/busboy-interceptor.test.spec.js
https://dojot.atlassian.net/browse/DOJOT-20
https://dojot.atlassian.net/browse/DOJOT-35
> [DOJOT-7] Fixes for 0.8.0-rc1

- iam/device-basic-authentication/app/db/controllers/BasicCredentialsCtrl.js
- iam/device-basic-authentication/app/db/models/BasicCredentials.js
- iam/device-basic-authentication/test/unit/BasicCredentialsCtrl.test.js
- iam/device-basic-authentication/test/unit/DeviceService.test.js
> [Device-basic-authentication] Devices can have only one credential saved

- storage/time-series/influxdb/storer/Dockerfile-dev
- storage/time-series/influxdb/storer/app/influx/DataWriter.js
- storage/time-series/influxdb/storer/app/influx/index.js
- storage/time-series/influxdb/storer/config/default.conf
- storage/time-series/influxdb/storer/package.json
- storage/time-series/influxdb/storer/test/unit/InfluxDataWriter.test.js
https://dojot.atlassian.net/browse/DOJOT-54
> [DOJOT-54] Update: Consider attribute types for persistence

- storage/time-series/influxdb/storer/app/influx/DataWriter.js
- storage/time-series/influxdb/storer/app/influx/Measurements.js
- storage/time-series/influxdb/storer/app/influx/Organizations.js
- storage/time-series/influxdb/storer/app/influx/index.js
- storage/time-series/influxdb/storer/config/default.conf
- storage/time-series/influxdb/storer/test/unit/InfluxDataWriter.test.js
- storage/time-series/influxdb/storer/test/unit/InfluxMeasurements.test.js
- storage/time-series/influxdb/storer/test/unit/InfluxOrganizations.test.js
…ile writing.
https://dojot.atlassian.net/browse/DOJOT-41
> [DOJOT-41] Fix: Adjusting settings to decrease timeout logs while writing.

- .github/workflows/keycloak-microservice-sidecar.yml
- .github/workflows/keycloak-proxy.yml
> Fix: github actions 2

- .github/workflows/keycloak-microservice-sidecar.yml
- .github/workflows/keycloak-proxy.yml
- iam/keycloak-proxy/src/index.js
- tools/keycloak-microservice-sidecar/src/index.js
> Fix: GitHub actions

- storage/time-series/influxdb/retriever/Dockerfile-dev
- storage/time-series/influxdb/retriever/app/App.js
- storage/time-series/influxdb/retriever/app/influx/DeviceDataRepository.js
- storage/time-series/influxdb/retriever/config/default.conf
- storage/time-series/influxdb/retriever/license-exceptions.json
- storage/time-series/influxdb/retriever/package-lock.json
- storage/time-series/influxdb/retriever/test/integration/RoutesV1Device.test.js
- storage/time-series/influxdb/retriever/test/unit/DeviceDataRepository.test.js
https://dojot.atlassian.net/browse/DOJOT-54
> [DOJOT-54] Update: Consider attribute types for retrieval

- storage/time-series/influxdb/retriever/package-lock.json
- storage/time-series/influxdb/retriever/package.json
https://jira.cpqd.com.br/browse/DEVOPS-273
> [DEVOPS-273] [influxdb-retriever] Fix: uuid sub-library

- connector/mqtt/vernemq/k2v-bridge/config/default.conf
- connector/mqtt/vernemq/k2v-bridge/dev-dockerfile
- connector/mqtt/vernemq/k2v-bridge/package.json
https://dojot.atlassian.net/browse/DOJOT-95
> [DOJOT-95] [k2v-bridge] Update: change device-manager.device topic to device-manager.configure

- connector/http-agent/app/Server.js
[#DOJOT-111](https://dojot.atlassian.net/browse/DOJOT-111)
> [Http-agent] http only mode must not depend on https

- .github/workflows/iam-keycloak.yml
> Adjust keycloak actions

- iam/device-basic-authentication/Dockerfile-dev
- iam/device-basic-authentication/app/axios/DeviceService.js
- iam/device-basic-authentication/app/db/models/BasicCredentials.js
- iam/device-basic-authentication/package-lock.json
- iam/device-basic-authentication/package.json
- iam/device-basic-authentication/test/unit/DeviceService.test.js
… all cases
https://dojot.atlassian.net/browse/DOJOT-191
> [DOJOT-191] [device-basic-authentication] Fix: response with "invalid device" for all cases

- storage/time-series/influxdb/telegraf/Dockerfile-dev
- storage/time-series/influxdb/telegraf/plugins/outputs/influxdb_vdojot/http.go
- storage/time-series/influxdb/telegraf/plugins/outputs/influxdb_vdojot/influxdb_vdojot.go
> Fix: repeatedly set prefix on data

- connector/http-agent/app/kafka/ConsumerMessages.js
https://dojot.atlassian.net/browse/DOJOT-191
> [DOJOT-191] Fix: Http-agent ack undefined

- data-visualization/reports/report-manager/cspell.json
- data-visualization/reports/report-manager/src/utils/Prisma.utils.ts
- data-visualization/reports/report-manager/tests/mocks/Config.mock.ts
- data-visualization/reports/report-manager/tests/units/utils/Prisma.utils.test.ts
Fix
Sonar cloud appointed some problems with the report-manager service.
The problems should be fixed.
No
> Fix - Report Manager Sonarcloud Problems

- iam/x509-identity-mgmt/js/src/notifications/TrustedCANofitier.js
https://dojot.atlassian.net/jira/software/c/projects/DOJOT/boards/5?modal=detail&selectedIssue=DOJOT-149
> [DOJOT-149] [x509-identity-mgmt] Fix: topic in kafka producer

- data-visualization/reports/report-manager/NOTICE.md
- data-visualization/reports/report-manager/cspell.json
- data-visualization/reports/report-manager/docs/swagger.yml
Fix
Missing schemas in swagger docs.
Schemas added
No
> Fix - Report Manager Docs

- connector/http-agent/Dockerfile
> [Http-agent] Fix: alpine container

- connector/http-agent/Dockerfile
- device/device-manager-batch/package-lock.json
- device/device-manager-batch/src/index.ts
https://dojot.atlassian.net/browse/DOJOT-214
Bug fix.
Não realizava a leitura das variáveis de ambiente.
Agora as variaveis de ambientes são lidas quando usa-se o prefixo "DEVICEMANAGERBATCH".
> [DOJOT- 214] Fix: in device-manager-natch env settings

- data-visualization/reports/report-manager/dockerfile
- data-visualization/reports/report-manager/package.json
- data-visualization/reports/report-manager/tests/units/app/services/Report.service.test.ts
- data-visualization/reports/report-manager/yarn.lock
Fix
Report manager was throwing an error when running seeds.
Now everything works. But I didn't find the problem origin. 
Updating the node version and the prisma version fixed.
I hope we don't have an error every time prisma updates. 
No
> Fix - Report Manager Prisma

- data-visualization/reports/report-manager/README.md
- data-visualization/reports/report-manager/cspell.json
- data-visualization/reports/report-manager/src/index.ts
Fix
Prefixo do logger incorreto
Prefixo do logger correto (sem underline)
No
https://dojot.atlassian.net/browse/DOJOT-241
> [DOJOT-241] Fix - Report Manager Logger Prefix

- device/device-manager-batch/src/app/services/templatesServices.ts
https://dojot.atlassian.net/browse/DOJOT-247
> [DOJOT-247] - Fix problem deleting templates with associated devices

- .github/workflows/cert-sidecar.yml
- .github/workflows/certificate-acl.yml
- .github/workflows/connector-http-agent.yml
- .github/workflows/connector-kafka2ftp.yml
- .github/workflows/device-basic-authentication.yml
- .github/workflows/device-manager-batch.yml
- .github/workflows/file-mgmt.yml
- .github/workflows/history-proxy.yml
- .github/workflows/influxdb-retriever.yaml
- .github/workflows/influxdb-storer.yaml
- .github/workflows/k2v-bridge.yml
- .github/workflows/kafka-ws.yml
- .github/workflows/keycloak-microservice-sidecar.yml
- .github/workflows/keycloak-proxy.yml
- .github/workflows/locust.yaml
- .github/workflows/report-manager.yml
- .github/workflows/v2k-bridge.yml
- .github/workflows/x509-identity-mgmt.yml
> Remove codecov from github actions

- .github/workflows/cert-sidecar.yml
- .github/workflows/certificate-acl.yml
- .github/workflows/connector-http-agent.yml
- .github/workflows/connector-kafka2ftp.yml
- .github/workflows/device-basic-authentication.yml
- .github/workflows/device-manager-batch.yml
- .github/workflows/file-mgmt.yml
- .github/workflows/history-proxy.yml
- .github/workflows/influxdb-retriever.yaml
- .github/workflows/influxdb-storer.yaml
- .github/workflows/k2v-bridge.yml
- .github/workflows/kafka-ws.yml
- .github/workflows/keycloak-microservice-sidecar.yml
- .github/workflows/keycloak-proxy.yml
- .github/workflows/locust.yaml
- .github/workflows/report-manager.yml
- .github/workflows/v2k-bridge.yml
- .github/workflows/x509-identity-mgmt.yml
- device/device-manager-batch/src/app/services/templatesServices.ts
https://dojot.atlassian.net/browse/DOJOT-247
> [DOJOT-247] - Fix problem deleting templates with devices associated
